spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: danafix
  datasource:
    url: jdbc:postgresql://localhost:5432/danafix-test
    driverClassName: org.postgresql.Driver
    username: postgres
    password: wahyu

server:
  port: 8282
  servlet:
    context-path: /danafix
